<?php

// function enqueue_vue_scripts() {
//     // wp_enqueue_script('vue-js', 'https://cdn.jsdelivr.net/npm/vue@3/dist/vue.global.js', [], null, true);
//     wp_enqueue_script('custom-vue-app', get_template_directory_uri() . '/assets/js/app.js', ['vue-js'], null, true);
//     // wp_enqueue_style('tailwind-css', 'https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css');
//     wp_enqueue_style('fontawesome', 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css');
// }
// add_action('wp_enqueue_scripts', 'enqueue_vue_scripts');


/**
 * Theme Functions
 */

// 1. Enqueue the compiled Tailwind CSS
function demnayhair_tailwind_enqueue_scripts() {
    // Dist file generated by "npm run build"
    wp_enqueue_style(
        'demnayhair-tailwind', 
        get_stylesheet_directory_uri() . '/dist/tailwind.css', 
        array(), 
        filemtime(get_stylesheet_directory() . '/dist/tailwind.css')
    );
    wp_enqueue_script(
        'alpinejs', 
        'https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js', 
        array(), 
        null, 
        true
    );
    wp_enqueue_style('fontawesome', 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css');
}
add_action('wp_enqueue_scripts', 'demnayhair_tailwind_enqueue_scripts');

// 2. Register Menus (e.g. Main Menu, Secondary, etc.)
function demnayhair_register_menus() {
    register_nav_menus(array(
        'primary-menu' => __('Primary Menu', 'demnayhair-tailwind'),
        'secondary-menu' => __('Secondary Menu', 'demnayhair-tailwind'),
    ));
}
add_action('after_setup_theme', 'demnayhair_register_menus');

// 3. Theme Supports (thumbnails, title-tag, etc.)
function demnayhair_theme_setup() {
    add_theme_support('title-tag');
    add_theme_support('post-thumbnails');
}
add_action('after_setup_theme', 'demnayhair_theme_setup');

